# Generated by Django 5.0.6 on 2024-06-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default='image.jpj', upload_to='Teams'),
        ),
        migrations.AlterField(
            model_name='portflolio_projecrs',
            name='image',
            field=models.ImageField(upload_to='Projects'),
        ),
    ]
