# Generated by Django 5.0.6 on 2024-06-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0004_teammember_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='facebook_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instragram_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linked_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
