# Generated by Django 5.0.6 on 2024-06-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0005_teammember_facebook_link_teammember_instragram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
