# Generated by Django 5.0.6 on 2024-06-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0006_teammember_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
        migrations.AddField(
            model_name='services',
            name='icon_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
