# Generated by Django 5.0.6 on 2024-06-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0007_remove_services_image_services_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
        migrations.AlterField(
            model_name='services',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
