# Generated by Django 5.0.6 on 2024-06-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0008_services_image_alter_services_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
