# Generated by Django 5.0.6 on 2024-06-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0009_services_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('max_price', models.PositiveIntegerField()),
                ('min_price', models.PositiveIntegerField()),
            ],
        ),
    ]
